# Generated by Django 6.1 on 2026-08-20 18:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'مدير النظام (الأدمن)'), ('STAFF', 'موظف شركة'), ('CLIENT', 'عميل')], default='CLIENT', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('SALE', 'عقد بيع'), ('RENT', 'عقد إيجار')], max_length=10, verbose_name='نوع العقد')),
                ('payment_system', models.CharField(choices=[('MONTHLY', 'شهري'), ('4_INSTALLMENTS', '4 دفعات (ربع سنوي)'), ('6_INSTALLMENTS', '6 دفعات (كل شهرين)'), ('LUMP_SUM', 'دفعة واحدة')], default='MONTHLY', max_length=20, verbose_name='نظام الدفع')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي المبلغ')),
                ('is_active', models.BooleanField(default=True, verbose_name='العقد ساري')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المسؤول')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ القسط')),
                ('due_date', models.DateField(verbose_name='تاريخ استحقاق القسط')),
                ('status', models.CharField(choices=[('PENDING', 'معلق (غير مدفوع)'), ('PAID', 'تم الدفع'), ('OVERDUE', 'متأخر')], default='PENDING', max_length=20, verbose_name='حالة الدفع')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ السداد الفعلي')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='properties.contract', verbose_name='العقد المرتبط')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقار')),
                ('description', models.TextField(verbose_name='التفاصيل')),
                ('listing_type', models.CharField(choices=[('ASSET', 'ملكية خاصة للشركه'), ('SALE', 'للبيع'), ('RENT', 'للإيجار')], max_length=20, verbose_name='نوع العرض')),
                ('status', models.CharField(choices=[('AVAILABLE', 'متاح'), ('RENTED', 'مؤجر'), ('SOLD', 'مباع'), ('MAINTENANCE', 'تحت الصيانة')], default='AVAILABLE', max_length=20, verbose_name='حالة العقار')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر / قيمة الإيجار')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المساحة (متر مربع)')),
                ('address', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول / المالك')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='properties.property', verbose_name='العقار المتعاقد عليه'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='صورة العقار')),
                ('is_main', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='العقار')),
            ],
        ),
    ]
