# Generated by Django 6.1 on 2026-08-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('MAINTENANCE', 'صيانة'), ('ELECTRICITY', 'كهرباء'), ('WATER', 'مياه'), ('OTHER', 'أخرى')], max_length=20, verbose_name='نوع المصروف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='تاريخ الفاتورة')),
                ('description', models.TextField(verbose_name='ملاحظات')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='properties.property')),
            ],
        ),
    ]
