# Generated by Django 6.1 on 2026-09-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'مدير النظام (الأدمن)'), ('STAFF', 'موظف شركة'), ('CLIENT', 'عميل'), ('OWNER', 'مالك / وسيط عقاري')], default='CLIENT', max_length=20),
        ),
    ]
